language: python

python:
  - 3.6

sudo: required
dist: trusty
addons:
  postgresql: "9.6"

services:
  - postgresql

env:
  - DJANGO_SETTINGS_MODULE="decide.settings"

install:
  - pip install -r requirements.txt

script:
  - python ./decide/manage.py makemigrations
  - python ./decide/manage.py migrate
  - python ./decide/manage.py test ./decide/mixnet

notifications:
  email: false
